import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
// import { Navbar } from './component/product-page/navbar'
// import Footer from "./component/product-page/footer"
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Ez-Rent | Login ',
  description: 'Generated by create next app',
}
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <link rel="icon" href="/EzrentFavicon.png" sizes="any" />

      <body className={inter.className}>

        <Providers>{children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;